export default {
    SET_NEWS: 'SET_NEWS',
    ADD_STUDENT: 'ADD_STUDENT',
    SET_STUDENT: 'SET_STUDENT',
    SET_ERROR: 'SET_ERROR',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_TOTAL_PAGES: 'SET_TOTAL_PAGES'
};